blank_issues_enabled: false
contact_links:
  - name: Chocolatey Community Assistance
    url: https://ch0.co/community
    about: For help or to provide feedback, please join us on the Chocolatey community discord server!
