name: New Chocolatey Package request
description: Submit a new piece of software to be packaged
title: "New Chocolatey Package Request:"
labels: ["chocolatey-package-automation"]
body:
  - type: markdown
    attributes:
      value: |
        Have software you'd like packaged with Chocolatey? Fill out the form below.

  - type: input
    id: packageid
    attributes:
      label: Package Id
      description: A relevant package id to give the package.
      placeholder: e.g. software-name
    validations:
      required: true

  - type: input
    id: packageversion
    attributes:
      label: Package Version
      description: The version of the software you want to package.
      placeholder: e.g. 1.2.3
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: Software Download Url
      description: This is the url to download the installer
      placeholder: https://dl.example.com/software.exe
    validations:
      required: true

  - type: input
    id: silentargs
    attributes:
      label: Silent Arguments
      description: Provide the arguments used to install the software silently
      placeholder: /qn /norestart
    validations:
      required: true

  - type: input
    id: validexitcodes
    attributes:
      label: Valid Exit Codes
      description: Provide the exit codes that indicate a successful installation.
      placeholder: 0, 3010
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: Software Author
      description: The author of the software.
      placeholder: e.g. Microsoft

  - type: dropdown
    id: installertype
    attributes:
      label: Installer Type
      description: Select the Installer type.
      options:
        - EXE
        - MSI
    validations:
      required: true

  - type: input
    id: softwarename
    attributes:
      label: Software Name
      description: The name of the software as it shows in Programs and Features.
      placeholder: e.g. Google Chrome.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Package Description
      description: Provide a brief description of the software.
      placeholder: e.g. This is a great software that does amazing things.
    validations:
      required: true