name: new-package-issue
on:
  issues:
    types: [opened]

defaults:
  run:
    shell: pwsh

jobs:
  create-package:
    if: contains(github.event.issue.labels.*.name, 'chocolatey-package-automation')
    runs-on: self-hosted
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags to ensure we can rebase the branch on main.

      - name: Comment on issue
        uses: peter-evans/create-or-update-comment@v4
        id: comment
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for your submission! A new package will be created based on the information provided.

          reactions: |
             rocket
             +1

      - name: Parse Issue Body
        id: body
        run: |
          $body = @'
          ${{ github.event.issue.body }}
          '@
          .\issueparser.ps1 -IssueBody $body

      - name: Make package from template
        id: package
        run: |
            $splat = @{
              PackageId = "${{ steps.body.outputs.packageid }}"
              PackageVersion = "${{ steps.body.outputs.packageversion }}"
              Url = "${{ steps.body.outputs.softwaredownloadurl }}"
              SoftwareName = "${{ steps.body.outputs.softwareName }}"
              SilentArgs = "${{ steps.body.outputs.silentarguments }}"
              ValidExitCodes = "${{ steps.body.outputs.validexitcodes }}"
              Author = "${{ steps.body.outputs.softwareauthor }}"
              InstallerType = "${{ steps.body.outputs.installertype }}"
              Description = "${{ steps.body.outputs.softwaredescription }}"
            }

            .\build.ps1 @splat
      - name: Publish package
        run: | 
          $splat = @{
            TempDir = "${{ steps.package.outputs.TempDir }}"
            Source = "${{ secrets.CHOCOLATEY_SOURCE }}"
            ApiKey = "${{ secrets.CHOCOLATEY_API_KEY }}"
          }

          .\publish.ps1 @splat
      - name: Update Issue Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.comment.outputs.comment-id }}
          body: |
            **UPDATE:**
            The package has been created and published!

            Install it with the following command:

            ```powershell
            choco install ${{ steps.body.outputs.packageid }} --version ${{ steps.body.outputs.packageversion }} --source="${{ secrets.CHOCOLATEY_SOURCE }}"
            ```
          reactions: |
            hooray

      - name: Close issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            The issue has been closed as the package has been created and published.
            Thank you for your contribution!
          labels: |
             package-published