name: new-package-issue
on:
  issues:
    types: [opened]

defaults:
  run:
    shell: pwsh

jobs:
  create-package:
    if: contains(github.event.issue.labels.*.name, 'chocolatey-package-automation')
    runs-on: windows-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags to ensure we can rebase the branch on main.

      - name: Comment on issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for your submission! A new package will be created based on the information provided.

          reactions: |
             rocket
             +1

      - name: Parse Issue Body
        id: body
        run: |
          $body = @'
          ${{ github.event.issue.body }}
          '@
          .\issueparser.ps1 -IssueBody $body

      - name: Make package from template
        id: package
        run: |
            $splat = @{
              PackageId = "`"${{ steps.body.outputs.PackageId }}`""
              PackageVersion = "`"${{ steps.body.outputs.PackageVersion }}`""
              Url = "`"${{ steps.body.outputs.Url }}`""
              SilentArgs = "`"${{ steps.body.outputs.SilentArgs }}`""
              Author = "`"${{ steps.body.outputs.Author }}`""
              InstallerType = "`"${{ steps.body.outputs.InstallerType }}`""
              Description = "`"${{ steps.body.outputs.Description }}`""
            }

            .\build.ps1 @splat
      - name: Publish package
        run: | 
          $splat = @{
            TempDir = "`"${{ steps.package.outputs.TempDir }}`""
            Source = "`"${{ secrets.CHOCOLATEY_SOURCE }}`""
            ApiKey = "`"${{ secrets.CHOCOLATEY_API_KEY }}`""
          }

          .\publish.ps1 @splat